---
- name: Tag example
  hosts: servera.lab.example.com
  tasks: 
     - name: 1st task 
       debug:
         msg: "This is 1st task"
       tags: task1

     - name: 2nd task 
       debug:
         msg: "This is 2rd task" 
       tags: task2

     - name: 3rd task 
       debug:
         msg: "This is 3rd task"
       tags: task3

     - name: 4th task 
       debug:
         msg: "This is 4th task"
       tags: task4
...
